# test_cross_renderer.jl — Lyr vs Mitsuba 3 pixel-level ground truth comparison
#
# Renders identical canonical scenes in Lyr and compares against pre-computed
# Mitsuba 3 reference renders (4096 spp). Lyr renders at 512 spp — enough to
# beat MC noise for RMSE comparison, 8x faster than matching Mitsuba's SPP.
#
# Reference renders: test/fixtures/mitsuba_reference/*.bin
# Generated by: scripts/mitsuba_reference.py

using Test
using Lyr
using Random: Xoshiro

import Lyr: active_bounding_box, PhaseFunction, IsotropicPhase, HenyeyGreensteinPhase

# ============================================================================
# Parameters
# ============================================================================

const XRES     = 256
const XSPP_SS  = 512   # single scatter — fast
const XSPP_MS  = 256   # multi scatter — more work per sample
const XRADIUS  = 10.0
const XSIGMA_T = 1.0
const XCAM_Z   = 40.0
const XFOV     = 40.0
const XREF_DIR = joinpath(@__DIR__, "fixtures", "mitsuba_reference")

# Constant white TF: disables color modulation → pure physical rendering
const _TF_WHITE = TransferFunction([
    ControlPoint(0.0, (1.0, 1.0, 1.0, 1.0)),
    ControlPoint(1.0, (1.0, 1.0, 1.0, 1.0))
])

# ============================================================================
# Scene builders
# ============================================================================

function _xr_fog_sphere(; sigma_t=XSIGMA_T, albedo=0.8,
                          phase::PhaseFunction=IsotropicPhase())
    sdf = create_level_set_sphere(center=(0.0, 0.0, 0.0), radius=XRADIUS, voxel_size=1.0)
    fog = sdf_to_fog(sdf)
    nano = build_nanogrid(fog.tree)
    mat = VolumeMaterial(_TF_WHITE;
                         sigma_scale=sigma_t,
                         emission_scale=1.0,
                         scattering_albedo=albedo,
                         phase_function=phase)
    (fog, nano, mat)
end

function _xr_camera()
    Camera((0.0, 0.0, XCAM_Z), (0.0, 0.0, 0.0), (0.0, 1.0, 0.0), XFOV)
end

function _xr_light(; intensity=(1.0, 1.0, 1.0))
    # Mitsuba direction=(0,0,-1) = light travels -Z. Lyr = toward light = (0,0,1)
    DirectionalLight((0.0, 0.0, 1.0), intensity)
end

function _xr_render(scene, method, spp; seed=UInt64(42))
    t0 = time_ns()
    img = render_volume(scene, method, XRES, XRES; spp=spp, seed=seed)
    dt = (time_ns() - t0) / 1e9
    mrays = XRES * XRES * spp / 1e6
    @info "Lyr render" method spp time_s=round(dt, digits=1) Mrays_per_s=round(mrays/dt, digits=1)
    img
end

# ============================================================================

@testset "Cross-Renderer: Lyr vs Mitsuba 3" begin

# ============================================================================
# Scene A: Single Scatter
# ============================================================================

@testset "Scene A: Single Scatter" begin
    ref_path = joinpath(XREF_DIR, "scene_A_single_scatter.bin")
    if !isfile(ref_path)
        @test_skip "Mitsuba reference not generated (run scripts/mitsuba_reference.py)"
        return
    end
    ref = read_float32_image(ref_path)
    @test size(ref) == (XRES, XRES)

    fog, nano, mat = _xr_fog_sphere(sigma_t=XSIGMA_T, albedo=0.8)
    scene = Scene(_xr_camera(), _xr_light(), VolumeEntry(fog, nano, mat))
    lyr = _xr_render(scene, SingleScatterTracer(), XSPP_SS)

    rmse = image_rmse(lyr, ref)
    @test rmse < 0.02  # MC noise from 512 vs 4096 spp
    @info "Scene A" rmse
end

# ============================================================================
# Scene B: Multi Scatter
# ============================================================================

@testset "Scene B: Multi Scatter" begin
    ref_path = joinpath(XREF_DIR, "scene_B_multi_scatter.bin")
    if !isfile(ref_path)
        @test_skip "Mitsuba reference not generated"
        return
    end
    ref = read_float32_image(ref_path)

    fog, nano, mat = _xr_fog_sphere(sigma_t=XSIGMA_T, albedo=1.0)
    scene = Scene(_xr_camera(), _xr_light(), VolumeEntry(fog, nano, mat))
    lyr = _xr_render(scene, ReferencePathTracer(max_bounces=64), XSPP_MS)

    rmse = image_rmse(lyr, ref)
    @test rmse < 0.06  # higher noise at 256 spp, albedo=1.0 needs many bounces
    @info "Scene B" rmse
end

# ============================================================================
# Scene C: White Furnace
# ============================================================================

@testset "Scene C: White Furnace" begin
    ref_path = joinpath(XREF_DIR, "scene_C_white_furnace.bin")
    if !isfile(ref_path)
        @test_skip "Mitsuba reference not generated"
        return
    end
    ref = read_float32_image(ref_path)

    fog, nano, mat = _xr_fog_sphere(sigma_t=XSIGMA_T, albedo=1.0)
    env = ConstantEnvironmentLight((1.0, 1.0, 1.0))
    scene = Scene(_xr_camera(), [env], VolumeEntry(fog, nano, mat))
    lyr = _xr_render(scene, ReferencePathTracer(max_bounces=64), XSPP_MS)

    rmse = image_rmse(lyr, ref)
    @test rmse < 0.10  # Lyr is analytically correct (all 1.0); RMSE is Mitsuba's MC noise
    @info "Scene C (white furnace)" rmse

    # Every pixel should be close to 1.0 (sphere invisible)
    max_dev = 0.0
    for i in eachindex(lyr)
        r, g, b = lyr[i]
        max_dev = max(max_dev, abs(r - 1.0), abs(g - 1.0), abs(b - 1.0))
    end
    @test max_dev < 0.15  # MC noise bound
    @info "Scene C max deviation from 1.0" max_dev
end

# ============================================================================
# Scene D: HG Phase Sweep
# ============================================================================

@testset "Scene D: HG Phase Sweep" begin
    for g in [0.0, 0.3, 0.7, 0.9]
        gs = replace("g$(round(g, digits=1))", "." => "p")
        ref_path = joinpath(XREF_DIR, "scene_D_hg_$(gs).bin")
        if !isfile(ref_path)
            @test_skip "Mitsuba reference not generated for g=$g"
            continue
        end
        ref = read_float32_image(ref_path)
        hg = g == 0.0 ? IsotropicPhase() : HenyeyGreensteinPhase(g)

        fog, nano, mat = _xr_fog_sphere(sigma_t=XSIGMA_T, albedo=0.8, phase=hg)
        scene = Scene(_xr_camera(), _xr_light(), VolumeEntry(fog, nano, mat))
        lyr = _xr_render(scene, SingleScatterTracer(), XSPP_SS)

        rmse = image_rmse(lyr, ref)
        @test rmse < 0.02
        @info "Scene D" g rmse
    end
end

end  # Cross-Renderer
